### Importing TensorFlow

In [31]:
import tensorflow as tf

In [32]:
print('TensorFlow Version : {}'.format(tf.__version__))
print('Eager execution is : {}'.format(tf.executing_eagerly()))
print('Keras Version : {}'.format(tf.keras.__version__))

TensorFlow Version : 2.1.0
Eager execution is : True
Keras Version : 2.2.4-tf


### The following code can be used to find out whether a CPU or GPU is in use and if it's a GPU, whether that GPU is #0.

In [33]:
var = tf.Variable([3,3])

In [34]:
if tf.test.is_gpu_available():
    print('Running on GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else:
    print('Running on CPU')

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
Running on CPU


### Declaring Eager variables

In [35]:
# Normal Python Variable
t0 = 24

# Way of tensors
t1 = tf.Variable(42) # rank 0 tensor
t2 = tf.Variable([[[0.,1.,2.],[3.,4.,5.]],[[6.,7.,8.],[9.,10.,11.]]]) # rank 3 tensor
t0,t1,t2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

### TensorFlow will infer the datatype, defaulting to tf.float32 and tf.32 for integers

In [36]:
f64 = tf.Variable(89,dtype = tf.float64)

In [37]:
print(f64.dtype)

<dtype: 'float64'>


### Declaring Tensorflow Constants

In [38]:
m_o_l = tf.constant(42)
m_o_l

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [39]:
m_o_l.numpy()

42

#### Tensorflow will infer the datatype, or it can be explicitly specified, as in the case of variable 

In [40]:
unit = tf.constant(1,dtype = tf.int64)
unit

<tf.Tensor: shape=(), dtype=int64, numpy=1>

### Shaping a Tensor 

In [41]:
t2 = tf.Variable([[[0.,1.,2.],[3.,4.,5.]],[[6.,7.,8.],[9.,10.,11.]]]) # tensor Variable
print(t2)

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>


In [42]:
r1 = tf.reshape(t2,[2,6])
print(r1.shape)

(2, 6)


In [43]:
r2 = tf.reshape(t2,[1,12])
print(r2.shape)

(1, 12)


### Ranking (dimensions) of a tensor

#### The rank of a tensor is the number of dimensions it has 

In [44]:
tf.rank(t2)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

### Specifying an element of a tensor 

In [45]:
t3 = t2[1,0,2]
t3

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [46]:
t3.numpy()

8.0

### Casting a tensor to NumPy/Python Variable 

In [47]:
print(t2.numpy())

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


In [48]:
print(t2[1,0,2].numpy())

8.0


### Finding the size (number of elements) of a  tensor

In [49]:
s = tf.size(t2).numpy()
print(s)

12


### Finding the datatype of a tensor 

In [50]:
t3.dtype

tf.float32

### Specifying element-wise primitive tensor operations 

#### These operations are specified using, the overloaded operators +,-,* and / as below 

In [51]:
t2.numpy()

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)

In [52]:
t2*t2

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[  0.,   1.,   4.],
        [  9.,  16.,  25.]],

       [[ 36.,  49.,  64.],
        [ 81., 100., 121.]]], dtype=float32)>

### Broadcasting

#### Element wise tensors operations support broadcasting it the same way that numpy arrays do.
#### The simplest way is of multiplying a tensor with scalar

In [53]:
t4 = t2 * 4
t4

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 0.,  4.,  8.],
        [12., 16., 20.]],

       [[24., 28., 32.],
        [36., 40., 44.]]], dtype=float32)>

### Transposing TensorFlow and Matrix Mutltiplication

In [54]:
u = tf.constant([[3,4,3]])
v = tf.constant([[1,2,1]])
print(tf.matmul(u,tf.transpose(a = v)))

tf.Tensor([[14]], shape=(1, 1), dtype=int32)


### Casting a tensor to another (tensor) data type

In [55]:
t1.dtype

tf.int32

In [56]:
i = tf.cast(t1, dtype = tf.int32)
i

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>

#### With truncation, it would be as follows

In [57]:
j = tf.cast(tf.constant(4.9),dtype = tf.int32)
j

<tf.Tensor: shape=(), dtype=int32, numpy=4>

### Declaring Ragged Tensors 

#### A Ragged tensor is a tensor with one or more ragged dimensions. Ragged dimensions are the dimensions that have slices of different lengths 

In [58]:
ragged =tf.ragged.constant([[5, 2, 6, 1], [], [4, 10, 7], [8], [6,7]])
print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>
tf.Tensor([5 2 6 1], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 4 10  7], shape=(3,), dtype=int32)
tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)


#### A common way of creating a ragged array is by using the tf.RaggedTensor.from_row_splits() method, which has the following signature:

### Finding the squared difference between two tensors

In [59]:
x = [1,3,5,7,11]
y = 5
s = tf.math.squared_difference(x,y)
s

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  4,  0,  4, 36], dtype=int32)>

In [60]:
x = [4,5,6,8,3]
y = 8
tf.math.squared_difference(x,y).numpy()

array([16,  9,  4,  0, 25], dtype=int32)

### Finding a Mean

In [61]:
numbers = tf.constant([[4.,5.],[7.,3.]])
tf.reduce_mean(input_tensor=numbers)

<tf.Tensor: shape=(), dtype=float32, numpy=4.75>

### Finding the mean across all axes

In [62]:
tf.reduce_mean(input_tensor=numbers)

<tf.Tensor: shape=(), dtype=float32, numpy=4.75>

### Finding the mean across the columns 

In [63]:
tf.reduce_mean(input_tensor=numbers,axis = 0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5.5, 4. ], dtype=float32)>

### Finding the mean across the rows

In [64]:
tf.reduce_mean(input_tensor=numbers,axis = 1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5. ], dtype=float32)>

### Generating Tensors filled with Random Values 

### Using tf.random.normal()
#### It outputs a tensor of the given shape filled with the values of the dtype type from a normal distribution

In [65]:
tf.random.normal(shape = (3,2),mean = 10, stddev=2,dtype = tf.float32,seed = None,name = None)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 7.775935, 10.725556],
       [ 6.561617,  6.861107],
       [11.420644, 12.455684]], dtype=float32)>

In [66]:
ran = tf.random.normal(shape=(3,2),mean=10.0,stddev=2.0, seed = None)
print(ran)

tf.Tensor(
[[ 9.80613   10.141904 ]
 [ 5.8037252 10.395583 ]
 [12.542021   6.8583016]], shape=(3, 2), dtype=float32)


### Using tf.random.uniform()

In [67]:
tf.random.uniform(shape=(3,2), minval=0, maxval=None, dtype = tf.float32)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.60703206, 0.06531429],
       [0.5927547 , 0.11209118],
       [0.13268876, 0.4533236 ]], dtype=float32)>

#### Note that, for both of these random operations, if you want the random values generated to be repeatable, then use tf.random.set_seed()

In [68]:
tf.random.set_seed(123)

In [69]:
ran1 = tf.random.uniform(shape = (4,4),minval=0,maxval=100,dtype = tf.int32)
print(ran1)

tf.Tensor(
[[81 78 14 28]
 [48 20 65 13]
 [72 67 36 94]
 [62 78 15 95]], shape=(4, 4), dtype=int32)


In [70]:
tf.random.set_seed(123)

In [71]:
ran2 = tf.random.uniform(shape = (4,4),minval=0,maxval=100,dtype = tf.int32)
print(ran2)

tf.Tensor(
[[81 78 14 28]
 [48 20 65 13]
 [72 67 36 94]
 [62 78 15 95]], shape=(4, 4), dtype=int32)


### Using a practical example of random values

In [72]:
dice1 = tf.Variable(tf.random.uniform(shape = (10,1), minval = 1, maxval = 6, dtype = tf.int32))
dice2 = tf.Variable(tf.random.uniform(shape = (10,1), minval = 1, maxval = 6, dtype = tf.int32))

In [73]:
# We may add dice1 and dice2 since they share the same shape and size
diceSum = dice1 + dice2

In [74]:
# We've got three separate 10x1 matrices. To produce a single
# 10x3 matrix, we'll concatenate them along dimension 1
resultingDice = tf.concat((dice1,dice2,diceSum),axis = 1)

In [75]:
resultingDice

<tf.Tensor: shape=(10, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 1,  5,  6],
       [ 5,  3,  8],
       [ 4,  1,  5],
       [ 1,  3,  4],
       [ 5,  2,  7],
       [ 1,  2,  3],
       [ 4,  4,  8],
       [ 5,  5, 10],
       [ 3,  2,  5]], dtype=int32)>

### Finding the indices of the largest and smallest element

In [92]:
t1 = tf.constant([1,2,3,4,5,6,7,8,9,1,2,3])

In [96]:
tf.argmax(t1,axis = 0)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

In [95]:
t1[8]

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [97]:
t1[8]

<tf.Tensor: shape=(), dtype=int32, numpy=9>

### Using tf.function

#### tf.function is a function that will take a Python function and return a TensorFlow graph. The advantage of this is that graphs can apply optimizations and exploit parallelism in the Python function (func). tf.function is new to TensorFlow 2.

In [99]:
def f1(x,y):
    return tf.reduce_mean(input_tensor=tf.multiply(x**2,5) + y**2)

In [100]:
f2 = tf.function(f1)

In [101]:
x = tf.constant([4., -5.]) 
y = tf.constant([2., 3.])

In [102]:
# f1 and f2 return the same value, but f2 executes as a TensorFlow graph

In [103]:
assert f1(x,y).numpy() == f2(x,y).numpy()

In [110]:
f2(x,y).numpy()

109.0

In [111]:
f1(x,y).numpy()

109.0