# Importing TensorFlow

In [18]:
import tensorflow as tf

In [19]:
print('TensorFlow Version : {}'.format(tf.__version__))
print('Eager execution is : {}'.format(tf.executing_eagerly()))
print('Keras Version : {}'.format(tf.keras.__version__))

TensorFlow Version : 2.1.0
Eager execution is : True
Keras Version : 2.2.4-tf


In [20]:
var = tf.Variable([3,3])

In [21]:
if tf.test.is_gpu_available():
    print('Running on GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else:
    print('Running on CPU')

Running on CPU


## Declaring Eager variables

In [22]:
# Normal Python Variable
t0 = 24
t1 = tf.Variable(42) # rank 0 tensor
t2 = tf.Variable([[[0.,1.,2.],[3.,4.,5.]],[[6.,7.,8.],[9.,10.,11.]]]) # rank 3 tensor
t0,t1,t2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

#### TensorFlow will infer the datatype, defaulting to tf.float32 and tf.32 for integers

In [23]:
f64 = tf.Variable(89,dtype = tf.float64)

In [24]:
print(f64.dtype)

<dtype: 'float64'>


## Declaring Tensorflow Constants

In [25]:
m_o_l = tf.constant(42)
m_o_l

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [26]:
m_o_l.numpy()

42

#### Tensorflow will infer the datatype, or it can be explicitly specified, as in the case of variable 

In [27]:
unit = tf.constant(1,dtype = tf.int64)
unit

<tf.Tensor: shape=(), dtype=int64, numpy=1>

## Shaping a Tensor 

In [28]:
t2 = tf.Variable([[[0.,1.,2.],[3.,4.,5.]],[[6.,7.,8.],[9.,10.,11.]]]) # tensor Variable
print(t2)

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>


In [29]:
r1 = tf.reshape(t2,[2,6])
print(r1.shape)

(2, 6)


In [30]:
r2 = tf.reshape(t2,[1,12])
print(r2.shape)

(1, 12)


## Ranking (dimensions) of a tensor

#### The rank of a tensor is the number of dimensions it has 

In [31]:
tf.rank(t2)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

## Specifying an element of a tensor 

In [32]:
t3 = t2[1,0,2]
t3

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

## Casting a tensor to NumPy/Python Variable 

In [33]:
print(t2.numpy())

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


In [34]:
print(t2[1,0,2].numpy())

8.0


## Finding the size (number of elements) of a  tensor

In [35]:
s = tf.size(t2).numpy()
print(s)

12


## Finding the datatype of a tensor 

In [36]:
t3.dtype

tf.float32

## Specifying element-wise primitive tensor operations 

#### These operations are specified using, the overloaded operators +,-,* and / as below 

In [53]:
t2*t2

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[  0.,   1.,   4.],
        [  9.,  16.,  25.]],

       [[ 36.,  49.,  64.],
        [ 81., 100., 121.]]], dtype=float32)>

## Broadcasting

#### Element wise tensors operations support broadcasting it the same way that numpy arrays do.
#### The simplest way is of multiplying a tensor with scalar

In [37]:
t4 = t2 * 4
t4

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 0.,  4.,  8.],
        [12., 16., 20.]],

       [[24., 28., 32.],
        [36., 40., 44.]]], dtype=float32)>

## Transposing TensorFlow and Matrix Mutltiplication

In [39]:
u = tf.constant([[3,4,3]])
v = tf.constant([[1,2,1]])
print(tf.matmul(u,tf.transpose(a = v)))

tf.Tensor([[14]], shape=(1, 1), dtype=int32)


## Casting a tensor to another (tensor) data type

In [40]:
i = tf.cast(t1, dtype = tf.int32)
i

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>

#### With truncation, it would be as follows

In [41]:
j = tf.cast(tf.constant(4.9),dtype = tf.int32)
j

<tf.Tensor: shape=(), dtype=int32, numpy=4>

## Declaring Ragged Tensors 

#### A Ragged tensor is a tensor with one or more ragged dimensions. Ragged dimensions are the dimensions that have slices of different lengths 

In [42]:
ragged =tf.ragged.constant([[5, 2, 6, 1], [], [4, 10, 7], [8], [6,7]])
print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>
tf.Tensor([5 2 6 1], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 4 10  7], shape=(3,), dtype=int32)
tf.Tensor([8], shape=(1,), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)


#### A common way of creating a ragged array is by using the tf.RaggedTensor.from_row_splits() method, which has the following signature:

## Finding the squared difference between two tensors

In [43]:
x = [1,3,5,7,11]
y = 5
s = tf.math.squared_difference(x,y)
s

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  4,  0,  4, 36], dtype=int32)>

### Finding a Mean

In [44]:
numbers = tf.constant([[4.,5.],[7.,3.]])
tf.reduce_mean(input_tensor=numbers)

<tf.Tensor: shape=(), dtype=float32, numpy=4.75>

## Finding the mean across all axes

In [45]:
tf.reduce_mean(input_tensor=numbers)

<tf.Tensor: shape=(), dtype=float32, numpy=4.75>

## Finding the mean across the columns 

In [46]:
tf.reduce_mean(input_tensor=numbers,axis = 0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5.5, 4. ], dtype=float32)>

## Finding the mean across the rows

In [47]:
tf.reduce_mean(input_tensor=numbers,axis = 1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5. ], dtype=float32)>

# Generating Tensors filled with Random Values 

## Using tf.random.normal()
#### It outputs a tensor of the given shape filled with the values of the dtype type from a normal distribution

In [48]:
tf.random.normal(shape = (3,2),mean = 10, stddev=2,dtype = tf.float32,seed = 123,name = None)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[14.887075 , 11.306596 ],
       [ 5.8247356,  8.706921 ],
       [11.007978 ,  8.675526 ]], dtype=float32)>

In [119]:
ran = tf.random.normal(shape=(3,2),mean=10.0,stddev=2.0, seed = 123)
print(ran)

tf.Tensor(
[[12.135355  11.318143 ]
 [ 9.75863    6.7020006]
 [15.011998   7.2023916]], shape=(3, 2), dtype=float32)
