### Loading Libraries

In [11]:
import tensorflow as tf
import numpy as np

In [12]:
num_items = 11
num_list1 = np.arange(num_items)
num_list2 = np.arange(num_items,num_items*2)

In [13]:
num_list1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
num_list2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

#### This is how to create datasets, using the from_tensor_slices() method: 

In [15]:
num_list1_dataset = tf.data.Dataset.from_tensor_slices(num_list1)

#### This is how to create an iterator on it using the make_one_shot_iterator() method: 

In [16]:
iterator = tf.compat.v1.data.make_one_shot_iterator(num_list1_dataset)

In [17]:
for item in num_list1_dataset:
    num = iterator.get_next().numpy()
    print(num)

0
1
2
3
4
5
6
7
8
9
10


#### Note that executing this code twice in the same program run will raise an error because we are using a one-shot iterator

#### It is also possible to access the data in batches with batch method. Note that first argument is the number of elements to put in each batch and the second is the self-explanatory drop_remainder argument

In [18]:
num_list1_dataset = tf.data.Dataset.from_tensor_slices(num_list1).batch(3,drop_remainder=False)

In [19]:
iterator = tf.compat.v1.data.make_one_shot_iterator(num_list1_dataset)

In [20]:
for item in num_list1_dataset:
    num = iterator.get_next().numpy()
    print(num)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10]
